### ISSUE TITLE
Swap some integers ?

### ISSUE THREAD

**Issue by Carreau** [adtac/exterminate#1]
CPython in particular is known to cache a lot of thing in particular integers from -5 to 250something. 

So technically you __can__ swap some integers so that `69 == 42` is `True` , or `41+1` is `36` (see [how to do it](https://jakevdp.github.io/blog/2014/05/09/why-python-is-slow/#Modifying-the-Value-of-an-Integer)).

That's a really bad idea though. You might not like it. 

May I suggest also for the random module to always return the same value. 

[4 is a good one](https://xkcd.com/221/)

**Comment by sayak-brm** [comment]
I want this!!!

**Comment by lathomas64** [comment]
I tried this but get errors about IntStruct not existing

**Comment by sils** [comment]
FWIW I have a PR here which essentially switches the behaviour of sorted and random.shuffle: https://github.com/adtac/destruction/pull/5

About switching out bool/int values the snippet from reddit seems to work for ints at least, see https://github.com/adtac/destruction/issues/4#issuecomment-285159742

**Comment by adtac** [comment]
Added [Alt29](https://github.com/adtac/exterminate/commit/67c68bbdd20571458de509e2c7e8c2691769af5e) (thanks to @sils)
